import { ReactNode } from 'react';
import { StyleSheet, View, Text, Pressable, ScrollView, TextInput, TextInputProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
export const colors={paper:'#f7f3e8',ink:'#203d30',muted:'#52634c',green:'#226345',line:'#d9dfcf',gold:'#e1bc70'};
export function Screen({title,children,back}:{title:string;children:ReactNode;back?:()=>void}) {return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">{back&&<Button label="← Back" onPress={back} secondary/>}<Text accessibilityRole="header" style={s.title}>{title}</Text>{children}</ScrollView></SafeAreaView>;}
export function Button({label,onPress,secondary,disabled}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}) {return <Pressable accessibilityRole="button" accessibilityState={{disabled:!!disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,(pressed||disabled)&&{opacity:.6}]}><Text style={[s.buttonText,secondary&&{color:colors.ink}]}>{label}</Text></Pressable>;}
export function Card({children}:{children:ReactNode}) {return <View style={s.card}>{children}</View>;}
export function Body({children}:{children:ReactNode}) {return <Text style={s.body}>{children}</Text>;}
export function Field({label,...props}:TextInputProps&{label:string}) {return <View style={{marginVertical:6}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} style={s.input} {...props}/></View>;}
export const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},page:{padding:22,paddingBottom:44,maxWidth:760,width:'100%',alignSelf:'center',gap:12},title:{fontSize:30,fontWeight:'700',color:colors.ink,marginVertical:10},body:{fontSize:16,lineHeight:25,color:colors.muted},card:{padding:18,borderRadius:20,backgroundColor:'#fffdf6',borderWidth:1,borderColor:colors.line,gap:10},button:{minHeight:50,padding:14,borderRadius:14,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},secondary:{backgroundColor:'#e8edde'},buttonText:{fontSize:16,fontWeight:'600',color:'white',textAlign:'center'},label:{color:colors.ink,fontSize:15,marginBottom:7},input:{borderWidth:1,borderColor:'#9baa96',backgroundColor:'#fffdf6',borderRadius:12,minHeight:50,padding:12,color:colors.ink,fontSize:17}});
